baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Mes howtos"
  #subtitle    = "Mes howtos"
  copyright   = "Â© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "ronron22"

  #logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your orgg"

  author = "AM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


